# TODO: 3 services: db, grpc-server (50051), gateway (8080)
services:
  db:
    image: postgres:17-alpine
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  grpc-server:
    build:
      context: .
      dockerfile: grpc_server/Dockerfile
    env_file:
      - .env
    ports:
      - "50051:50051"
    depends_on:
      db:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      grpc-server:
        condition: service_started

volumes:
  postgres_data:
