# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node_registry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'node_registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13node_registry.proto\x12\rnode_registry\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n\x0cNodeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x1a\n\nGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\rDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"6\n\x08NodeList\x12*\n\x05nodes\x18\x01 \x03(\x0b\x32\x1b.node_registry.NodeResponse\"\x07\n\x05\x45mpty2\x8b\x02\n\x0cNodeRegistry\x12G\n\x08Register\x12\x1e.node_registry.RegisterRequest\x1a\x1b.node_registry.NodeResponse\x12\x35\n\x04List\x12\x14.node_registry.Empty\x1a\x17.node_registry.NodeList\x12=\n\x03Get\x12\x19.node_registry.GetRequest\x1a\x1b.node_registry.NodeResponse\x12<\n\x06\x44\x65lete\x12\x1c.node_registry.DeleteRequest\x1a\x14.node_registry.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODERESPONSE']._serialized_start=72
  _globals['_NODERESPONSE']._serialized_end=252
  _globals['_REGISTERREQUEST']._serialized_start=254
  _globals['_REGISTERREQUEST']._serialized_end=313
  _globals['_GETREQUEST']._serialized_start=315
  _globals['_GETREQUEST']._serialized_end=341
  _globals['_DELETEREQUEST']._serialized_start=343
  _globals['_DELETEREQUEST']._serialized_end=372
  _globals['_NODELIST']._serialized_start=374
  _globals['_NODELIST']._serialized_end=428
  _globals['_EMPTY']._serialized_start=430
  _globals['_EMPTY']._serialized_end=437
  _globals['_NODEREGISTRY']._serialized_start=440
  _globals['_NODEREGISTRY']._serialized_end=707
# @@protoc_insertion_point(module_scope)
